### ISSUE TITLE
Replace Travis CI with Github Actions

### ISSUE THREAD

**Issue by abdulhannanali** [lirantal/lockfile-lint#109]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Github Actions are more integrated than Travis CI, so I thought if this is something you'd like to consider 

**Describe alternatives you've considered**
None

**Comment by lirantal** [comment]
Yes, let's do that!
@abdulhannanali will you come up with a PR? I have a bunch of GitHub Actions workflows in my other repos if you needed some reference starting point to get started.

**Comment by abdulhannanali** [comment]
@lirantal Awesome, I will check them out

**Comment by jelhan** [comment]
I think this issue could be closed since #110 has been merged.
