### ISSUE TITLE
Epic: enable fearless cooperation 

### ISSUE THREAD

**Issue by naugtur** [lirantal/lockfile-lint#124]
What's [fearless cooperation](https://agoric.com/assets/pdf/FearlessCooperation-SES-BrianWarner-Agoric-DWeb2018.pdf)? It's running 3rd-party code in a way you benefit from it but without risking anything worse than an error being thrown if it turns malicious.

Initial scope limited to lockfile-lint-api package

- [x] #122 
- [x] #123 
- [x] #125 

Changes proposed:
- #126 
- #127

**Comment by naugtur** [comment]
@lirantal

**Comment by lirantal** [comment]
Nice work, thanks for bringing this up.

**Comment by lirantal** [comment]
Looks like we're good here so I'm closing the issue.
