### ISSUE TITLE
Friendlier error message when parsing lock files fails

### ISSUE THREAD

**Issue by lirantal** [lirantal/lockfile-lint#16]
**Is your feature request related to a problem? Please describe.**
When parsing files of either npm or yarn lockfile, let's make sure we show a friendly error message instead of the general error exception being thrown.

This is in continuation to #9 and the work landed by @emimuresan in #13 

**Describe the solution you'd like**
This should probably be done at the level of `ParseLockfile.js` class l

**Comment by emimuresan** [comment]
I will take a look 👍
