### ISSUE TITLE
Use log symbols for easier to read output

### ISSUE THREAD

**Issue by emimuresan** [lirantal/lockfile-lint#21]
**Is your feature request related to a problem? Please describe.**
1. More friendly and easier to read output. 
2. Also in case of no issues found, a success message should be printed - right now i don't see any message if all is ok.

**Describe the solution you'd like**
Use something like: https://www.npmjs.com/package/log-symbols

**Describe alternatives you've considered**
Alternative solution, styling the text: https://www.npmjs.com/package/ansi-colors, though i think the symbols are better.

**Comment by lirantal** [comment]
Sure we can try to spicy things up a bit.
Did you have a particular format in mind for how errors would look like? I agree about having a success message too and formatting that is pretty straight-forward.

**Comment by lirantal** [comment]
@emimuresan happy to add it if you wanted to give a chance for a PR

**Comment by XhmikosR** [comment]
This should fix the Windows situation too where right now no symbols are shown, because Windows native CLI is inherently broken :)

**Comment by emimuresan** [comment]
Hi @XhmikosR , i opened a PR for this (included Windows support).

**Comment by lirantal** [comment]
Thanks for getting back to this one! 👏🏼

**Comment by glensc** [comment]
a sysmbols typo appeared in changelog.md

**Comment by lirantal** [comment]
@glensc could you point me to what you're referring to?

**Comment by glensc** [comment]
@lirantal:
- https://github.com/lirantal/lockfile-lint/search?q=sysmbols

**Comment by lirantal** [comment]
OH I see. Thanks for flagging. I guess there's no other way of really fixing it except than editing the Changelog file which I think we can skip at this point.

**Comment by glensc** [comment]
yes. only changelog file could be fixed
