### ISSUE TITLE
"Only yarn supported"?

### ISSUE THREAD

**Issue by matthias-ccri** [lirantal/lockfile-lint#45]
Hello!

The readme states:
> NOTE: currently only yarn's yarn.lock is supported. PRs to support npm's package-lock.json are welcome

This seems like old information, since the `lockfile-lint` package does support npm lockfiles, though I may be wrong. 

So in this issue, I want to ask: is this readme statement correct?

**Comment by lirantal** [comment]
Oh you're right! README is definitely old since npm's `package-lock.json` is supported as well. Would you want to submit a quick PR to fix it (remove that note) ?

**Comment by matthiasdailey-ccri** [comment]
Sure thing: https://github.com/lirantal/lockfile-lint/pull/46
