### ISSUE TITLE
Support for pnp and npm-shrinkwrap

### ISSUE THREAD

**Issue by DanielRuf** [lirantal/lockfile-lint#5]
**Is your feature request related to a problem? Please describe.**
Currently only package-lock.json and yarn.lock are checked. But npm-shrinkwrap.json is not which gets higher priority than package-lock.json.

https://docs.npmjs.com/cli/shrinkwrap.html

Also add support for Yarn PnP.

**Describe the solution you'd like**
Support for more lockfile types, especially npm-shrinkwrap.

**Comment by lirantal** [comment]
Updated docs as to the supported lockfiles.
PnP isn't supported to closing this with no further updates.
