### ISSUE TITLE
Bug: only one file checked

### ISSUE THREAD

**Issue by DanielRuf** [lirantal/lockfile-lint#6]
## Expected Behavior

If there are multiple lockfiles like we use at zurb/foundation-sites, only one will be checked.

## Current Behavior

Only one / first found lockfile is checked as it seems.

https://github.com/lirantal/lockfile-lint/blob/master/packages/lockfile-lint-api/src/ParseLockfile.js

## Possible Solution

Test all found lockfiles.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Hard to check all at once. Can be used to change two files and only inject URLs in the second.

## Your Environment

- Library Version used:
- Node.js version (e.g. Node.js 5.4):
- Operating System and version (desktop or mobile):

**Comment by lirantal** [comment]
@DanielRuf 
1. What is the use-case of using several lockfiles for a project?
2. As a workaround you could lint them one by one

**Comment by DanielRuf** [comment]
> What is the use-case of using several lockfiles for a project?

Same setup for all consumers (of the app), see https://github.com/zurb/foundation-sites

**Comment by lirantal** [comment]
When you say to all consumers do you mean for those using "npm" and also for those using "yarn" ?

**Comment by DanielRuf** [comment]
And pnpm, Yarn PnP and so on. Yes. We normally update all of them at the same time.

**Comment by lirantal** [comment]
Closing due to work on this being handled with https://github.com/lirantal/lockfile-lint/issues/47
