### ISSUE TITLE
File-based configuration

### ISSUE THREAD

**Issue by mtlewis** [lirantal/lockfile-lint#74]
First off, thanks for this super useful tool.

**Is your feature request related to a problem? Please describe.**
Sharing lockfile-lint configuration is currently problematic, because the only way to configure it is via command-line arguments. If it were possible to store this configuration in a file, it would allow sharing that file amongst multiple repositories. It would also have the additional benefit of allowing commentary justifying the configuration choices made.

**Describe the solution you'd like**
The solution should probably use a third-party library for loading config, to allow loading config from multiple conventional sources without a bunch of work.

**Describe alternatives you've considered**
It would be possible to achieve a similar outcome by passing around scripts that wrap calls to lockfile-lint.

**Comment by lirantal** [comment]
Sounds like a great new feature, thanks for suggesting this @mtlewis 🎉
