### ISSUE TITLE
Allow ignoring `dev` dependencies in a lockfile

### ISSUE THREAD

**Issue by lirantal** [lirantal/lockfile-lint#8]
**Is your feature request related to a problem? Please describe.**
Allowing to ignore dev related dependencies in a lockfile might be useful due to fs file linking and other related usages.

**Comment by gagyibenedek** [comment]
I'll jump on this :)

**Comment by lirantal** [comment]
Closing due to less of public interest in pursuing this.
Re-opens are welcome.
