### ISSUE TITLE
lockfile-lint-api@^5.1.3 not published

### ISSUE THREAD

**Issue by mnahkies** [lirantal/lockfile-lint#92]
The version of `lockfile-lint-api@5.1.3 that should have been published by this commit 12 days ago:
https://github.com/lirantal/lockfile-lint/commit/a939b5fa0af060970f8b9511d1204e0b569fcd4b

Does not appear to have been.

The new version of `lockfile-lint` that was published this morning depends on this version, and now fails to install - can you please check this, and publish the required version of `lockfile-lint-api`

**Comment by lirantal** [comment]
Looking into it now

**Comment by lirantal** [comment]
Triggered a build now for release too, let's see if it bumps packages: https://travis-ci.org/github/lirantal/lockfile-lint/builds/686460434

**Comment by lirantal** [comment]
lockfile-lint@4.3.3 and lockfile-lint-api@5.1.5 released
@mnahkies can you confirm things are ok?

**Comment by krzysztofwolski** [comment]
Works for me now.

**Comment by mnahkies** [comment]
Yep works fine now thanks @lirantal

**Comment by lirantal** [comment]
Thanks for chiming in here. Sincerely appreciate that 🙏
